version: '3.4'
services:
  mysql:
    image: mariadb:10.3
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    env_file:
      - docker-compose.env
  wikibase:
    image: gremid/wikibase-lexeme-bundle
    build:
      context: .
    ports:
      - 80:80
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - web:/var/www/html/:rw
      - ./wikibase/LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php
    env_file:
      - docker-compose.env
volumes:
  web:
  db:
