---
- hosts: wb_sandbox
  tasks:
    - name: Create data directories
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "0770"
        state: directory
      with_items:
        - path: "/data"
          owner: root
          group: root
        - path: "/data/db"
          owner: 999
          group: 999
    - name: Configure Wikibase
      template:
        src: LocalSettings.php.j2
        dest: /data/LocalSettings.php
        owner: root
        group: root
        mode: "0664"
    - name: Create Docker network
      docker_network:
        name: wb_sandbox
    - name: Deploy MariaDB
      docker_container:
        name: wb_sb_db
        image: mariadb:10.3
        restart_policy: always
        networks:
          - name: wb_sandbox
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: "wikibase"
          MYSQL_USER: "wikibase"
          MYSQL_PASSWORD: "{{ wb_sandbox_db_password }}"
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
          - "/data/db:/var/lib/mysql"
    - name: Deploy Wikibase
      docker_container:
        name: wb_sb_wikibase
        image: gremid/wikibase-lexeme-bundle
        restart_policy: always
        networks:
          - name: wb_sandbox
        ports:
          - "8080:80"
        env:
          MW_SITE_NAME: "wb-sandbox"
          MW_SITE_LANG: "en"
          MW_ADMIN_NAME: "admin"
          MW_ADMIN_PASS: "{{ wb_sandbox_wb_admin_password }}"
          MW_ADMIN_EMAIL: "admin@example.com"
          MW_SECRET_KEY: "{{ wb_sandbox_wb_secret_key }}"
          MW_WG_SECRET_KEY: "{{ wb_sandbox_wb_secret_key }}"
          MW_WG_ENABLE_UPLOADS: "false"
          MW_WG_JOB_RUN_RATE: "0"
          MAX_JOBS: "1"
          DB_SERVER: "wb_sb_db:3306"
          DB_NAME: "wikibase"
          DB_USER: "wikibase"
          DB_PASS: "{{ wb_sandbox_db_password }}"
          WIKIBASE_PINGBACK: "false"
          WIKIBASE_HOST: "wb-sandbox.middell.net"
          WIKIBASE_PORT: "443"
        volumes:
           - "/data/LocalSettings.php:/var/www/html/LocalSettings.d/LocalSettings.override.php"
